### ISSUE TITLE
Open enum support

### ISSUE THREAD

**Issue by ychyrski** [brutusin/json-forms#68]
Having this schema 
```javascript
{
    "$schema": "http://json-schema.org/draft-03/schema#",
    "type": "object",
    "properties": {
        "species": {
            "title": "Species",     
            "type": "string",
            "enum": [
                "human",
                "dog",
                "cat"
            ],
            "required": true
        }       
    }
}
```

I would like to render a dropdown componet which would contain values from the enum section(human,cat,dog) and provide end user with the possibility to enter its own value. Any insights how to do so?

**Comment by idelvall** [comment]
This constraint can not be modeled with a json schema.
You can fix the values to only a valid set (using enum), or you can leave it open (without enum) , but you can not have both.
Said that, you can create your own json schema extension for that, and use your own keyword instead of 'enum', for example 'preferred', and then add a custom decorator to the library to achieve the desired graphical effect.

For custom decorater examples see :
* https://github.com/brutusin/json-forms#static-members
* http://brutusin.org/json-forms/#9

**Comment by ychyrski** [comment]
thanks!
